"""create initial schema

Revision ID: 5fc366a3fb08
Revises: 
Create Date: 2026-04-21 14:02:52.609189
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5fc366a3fb08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='contentstatus_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('cover_path', sa.String(length=1024), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('slug', name=op.f('uq_courses_slug'))
    )
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.create_table('modules',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='contentstatus_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_modules_position_non_negative')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_modules_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules'))
    )
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_index('ix_modules_course_id_position', 'modules', ['course_id', 'position'], unique=False)
    op.create_index(op.f('ix_modules_status'), 'modules', ['status'], unique=False)
    op.create_table('resources',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('pdf', 'video_local', 'file_attachment', 'link_placeholder', name='resourcetype_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='contentstatus_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_resources_duration_non_negative')),
    sa.CheckConstraint('page_count IS NULL OR page_count >= 0', name=op.f('ck_resources_page_count_non_negative')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_resources_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_resources_module_id_modules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index(op.f('ix_resources_course_id'), 'resources', ['course_id'], unique=False)
    op.create_index(op.f('ix_resources_module_id'), 'resources', ['module_id'], unique=False)
    op.create_index('ix_resources_module_id_type', 'resources', ['module_id', 'resource_type'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_table('resource_outline_items',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('time_start_seconds', sa.Integer(), nullable=True),
    sa.Column('time_end_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', 'review', 'hard', name='progressstatus_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_type', sa.Enum('parsed', 'manual', name='outlinesourcetype_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(time_start_seconds IS NULL OR time_start_seconds >= 0) AND (time_end_seconds IS NULL OR time_end_seconds >= 0)', name=op.f('ck_resource_outline_items_time_offsets_non_negative')),
    sa.CheckConstraint('page_number IS NULL OR page_number > 0', name=op.f('ck_resource_outline_items_page_number_positive')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_resource_outline_items_position_non_negative')),
    sa.CheckConstraint('time_start_seconds IS NULL OR time_end_seconds IS NULL OR time_end_seconds >= time_start_seconds', name=op.f('ck_resource_outline_items_time_range_valid')),
    sa.ForeignKeyConstraint(['parent_id'], ['resource_outline_items.id'], name=op.f('fk_resource_outline_items_parent_id_resource_outline_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_outline_items_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_outline_items'))
    )
    op.create_index(op.f('ix_resource_outline_items_parent_id'), 'resource_outline_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_resource_outline_items_resource_id'), 'resource_outline_items', ['resource_id'], unique=False)
    op.create_index('ix_resource_outline_items_resource_id_parent_id_position', 'resource_outline_items', ['resource_id', 'parent_id', 'position'], unique=False)
    op.create_index(op.f('ix_resource_outline_items_source_type'), 'resource_outline_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_resource_outline_items_status'), 'resource_outline_items', ['status'], unique=False)
    op.create_table('study_sessions',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.Enum('reading', 'video', 'review', 'practice', 'note_taking', name='sessiontype_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('timer_mode', sa.Enum('free', 'pomodoro', name='timermode_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('work_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('break_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cycles_completed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('break_interval_seconds IS NULL OR break_interval_seconds >= 0', name=op.f('ck_study_sessions_break_interval_non_negative')),
    sa.CheckConstraint('cycles_completed IS NULL OR cycles_completed >= 0', name=op.f('ck_study_sessions_cycles_non_negative')),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_study_sessions_duration_non_negative')),
    sa.CheckConstraint('work_interval_seconds IS NULL OR work_interval_seconds > 0', name=op.f('ck_study_sessions_work_interval_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_study_sessions_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_study_sessions_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_study_sessions_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index(op.f('ix_study_sessions_course_id'), 'study_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_module_id'), 'study_sessions', ['module_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_resource_id'), 'study_sessions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_session_type'), 'study_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_study_sessions_started_at'), 'study_sessions', ['started_at'], unique=False)
    op.create_index('ix_study_sessions_started_at_session_type', 'study_sessions', ['started_at', 'session_type'], unique=False)
    op.create_index(op.f('ix_study_sessions_timer_mode'), 'study_sessions', ['timer_mode'], unique=False)
    op.create_table('anchors',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('anchor_type', sa.Enum('pdf_page', 'pdf_text', 'video_timestamp', 'video_range', 'outline_item', name='anchortype_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text_excerpt', sa.Text(), nullable=True),
    sa.Column('selection_data', sa.JSON(), nullable=True),
    sa.Column('time_start_seconds', sa.Integer(), nullable=True),
    sa.Column('time_end_seconds', sa.Integer(), nullable=True),
    sa.Column('outline_item_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(time_start_seconds IS NULL OR time_start_seconds >= 0) AND (time_end_seconds IS NULL OR time_end_seconds >= 0)', name=op.f('ck_anchors_time_offsets_non_negative')),
    sa.CheckConstraint('page_number IS NULL OR page_number > 0', name=op.f('ck_anchors_page_number_positive')),
    sa.CheckConstraint('time_start_seconds IS NULL OR time_end_seconds IS NULL OR time_end_seconds >= time_start_seconds', name=op.f('ck_anchors_time_range_valid')),
    sa.ForeignKeyConstraint(['outline_item_id'], ['resource_outline_items.id'], name=op.f('fk_anchors_outline_item_id_resource_outline_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_anchors_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anchors'))
    )
    op.create_index(op.f('ix_anchors_anchor_type'), 'anchors', ['anchor_type'], unique=False)
    op.create_index(op.f('ix_anchors_outline_item_id'), 'anchors', ['outline_item_id'], unique=False)
    op.create_index(op.f('ix_anchors_resource_id'), 'anchors', ['resource_id'], unique=False)
    op.create_index('ix_anchors_resource_id_anchor_type', 'anchors', ['resource_id', 'anchor_type'], unique=False)
    op.create_table('attachments',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('outline_item_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('course_id IS NOT NULL OR module_id IS NOT NULL OR resource_id IS NOT NULL OR outline_item_id IS NOT NULL', name=op.f('ck_attachments_has_owner')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_attachments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_attachments_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outline_item_id'], ['resource_outline_items.id'], name=op.f('fk_attachments_outline_item_id_resource_outline_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_attachments_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_course_id'), 'attachments', ['course_id'], unique=False)
    op.create_index(op.f('ix_attachments_module_id'), 'attachments', ['module_id'], unique=False)
    op.create_index(op.f('ix_attachments_outline_item_id'), 'attachments', ['outline_item_id'], unique=False)
    op.create_index(op.f('ix_attachments_resource_id'), 'attachments', ['resource_id'], unique=False)
    op.create_table('annotations',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('anchor_id', sa.Integer(), nullable=True),
    sa.Column('annotation_type', sa.Enum('quick_note', 'bookmark', 'comment', 'question', 'summary', 'review_item', name='annotationtype_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='annotationstatus_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], name=op.f('fk_annotations_anchor_id_anchors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_annotations_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_annotations_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_annotations_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations'))
    )
    op.create_index(op.f('ix_annotations_anchor_id'), 'annotations', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_annotations_annotation_type'), 'annotations', ['annotation_type'], unique=False)
    op.create_index(op.f('ix_annotations_course_id'), 'annotations', ['course_id'], unique=False)
    op.create_index('ix_annotations_course_id_status', 'annotations', ['course_id', 'status'], unique=False)
    op.create_index(op.f('ix_annotations_module_id'), 'annotations', ['module_id'], unique=False)
    op.create_index(op.f('ix_annotations_resource_id'), 'annotations', ['resource_id'], unique=False)
    op.create_index('ix_annotations_resource_id_annotation_type', 'annotations', ['resource_id', 'annotation_type'], unique=False)
    op.create_index(op.f('ix_annotations_status'), 'annotations', ['status'], unique=False)
    op.create_table('progress_records',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('outline_item_id', sa.Integer(), nullable=True),
    sa.Column('anchor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', 'review', 'hard', name='progressstatus_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('last_interacted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('course_id IS NOT NULL OR module_id IS NOT NULL OR resource_id IS NOT NULL OR outline_item_id IS NOT NULL OR anchor_id IS NOT NULL', name=op.f('ck_progress_records_has_target')),
    sa.CheckConstraint('progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100)', name=op.f('ck_progress_records_progress_percent_range')),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], name=op.f('fk_progress_records_anchor_id_anchors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_progress_records_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_progress_records_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outline_item_id'], ['resource_outline_items.id'], name=op.f('fk_progress_records_outline_item_id_resource_outline_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_progress_records_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_records'))
    )
    op.create_index(op.f('ix_progress_records_anchor_id'), 'progress_records', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_progress_records_course_id'), 'progress_records', ['course_id'], unique=False)
    op.create_index(op.f('ix_progress_records_last_interacted_at'), 'progress_records', ['last_interacted_at'], unique=False)
    op.create_index(op.f('ix_progress_records_module_id'), 'progress_records', ['module_id'], unique=False)
    op.create_index(op.f('ix_progress_records_outline_item_id'), 'progress_records', ['outline_item_id'], unique=False)
    op.create_index(op.f('ix_progress_records_resource_id'), 'progress_records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_progress_records_status'), 'progress_records', ['status'], unique=False)
    op.create_index('ix_progress_records_status_last_interacted_at', 'progress_records', ['status', 'last_interacted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_progress_records_status_last_interacted_at', table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_status'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_resource_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_outline_item_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_module_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_last_interacted_at'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_course_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_anchor_id'), table_name='progress_records')
    op.drop_table('progress_records')
    op.drop_index(op.f('ix_annotations_status'), table_name='annotations')
    op.drop_index('ix_annotations_resource_id_annotation_type', table_name='annotations')
    op.drop_index(op.f('ix_annotations_resource_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_module_id'), table_name='annotations')
    op.drop_index('ix_annotations_course_id_status', table_name='annotations')
    op.drop_index(op.f('ix_annotations_course_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_annotation_type'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_anchor_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_attachments_resource_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_outline_item_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_module_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_course_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_anchors_resource_id_anchor_type', table_name='anchors')
    op.drop_index(op.f('ix_anchors_resource_id'), table_name='anchors')
    op.drop_index(op.f('ix_anchors_outline_item_id'), table_name='anchors')
    op.drop_index(op.f('ix_anchors_anchor_type'), table_name='anchors')
    op.drop_table('anchors')
    op.drop_index(op.f('ix_study_sessions_timer_mode'), table_name='study_sessions')
    op.drop_index('ix_study_sessions_started_at_session_type', table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_started_at'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_session_type'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_resource_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_module_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_course_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_resource_outline_items_status'), table_name='resource_outline_items')
    op.drop_index(op.f('ix_resource_outline_items_source_type'), table_name='resource_outline_items')
    op.drop_index('ix_resource_outline_items_resource_id_parent_id_position', table_name='resource_outline_items')
    op.drop_index(op.f('ix_resource_outline_items_resource_id'), table_name='resource_outline_items')
    op.drop_index(op.f('ix_resource_outline_items_parent_id'), table_name='resource_outline_items')
    op.drop_table('resource_outline_items')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index('ix_resources_module_id_type', table_name='resources')
    op.drop_index(op.f('ix_resources_module_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_course_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_modules_status'), table_name='modules')
    op.drop_index('ix_modules_course_id_position', table_name='modules')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###

